### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by reinhardt** [RedTurtle/Products.AutoRoleFromHostHeader#2]
Are there plans to support python 3?

**Comment by cekk** [comment]
Sure, if you make a pull-request we could add python 3 support ;)

Joking apart, we are using it only in an old Plone4 website and i don't know if there are some plans for future migrations, so this product is not in an active development status right now.

If you want to improve it, feel free to open a pr

**Comment by reinhardt** [comment]
Thanks! I may do just that. :-) We're using it in a site that we're upgrading to Plone 5.2/Python 3 and it could well be our best option to create that PR.

**Comment by reinhardt** [comment]
First step: #3 :-)

**Comment by cekk** [comment]
I've released a new version with your changes..can we close this issue?

Thanks!

**Comment by reinhardt** [comment]
Awesome, cheers!
